[package]
name = "common"
version = "0.1.0"
authors = ["Shannon Pace <futufeld@gmail.com>"]

[lib]
name = "common"
path = "lib.rs"

[dependencies.linalg]
path = "../../linalg"

[dependencies.utilities]
path = "../../utilities"
