[package]
name = "utilities"
version = "1.0.0"
authors = ["Shannon Pace <futufeld@gmail.com>"]

[lib]
name = "utilities"
path = "lib.rs"

[dependencies.linalg]
path = "../linalg"

[dependencies]
getopts = "0.2"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "*"
